name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: download pvsl
      run: curl -o pvsl https://github.com/nArnoSNES/snesdtc/releases/download/v2.3.2/pvsl
    - name: download snesdtb
      run: curl -o snesdtb.deb https://github.com/nArnoSNES/snesdtb/releases/download/v1.0-4/snesdtb_1.0-4.deb
    - name: extract pvsl
      run: sudo chmod +x pvsl && ./pvsl
    - name: install snesdtb
      run: sudo dpkg -i snesdtb.deb
    - name: make clean
      run: make clean
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
